### ISSUE TITLE
Roll mode in Pattern Play mode after starting the sequencer from MIDI slave mode is slightly bugged

### ISSUE THREAD

**Issue by gihaume** [HomoElectromagneticus/Yocto_808#18]
The time division selection with the Tempo encoder works in a bad way.

**Comment by rv0** [comment]
please explain?

**Comment by gihaume** [comment]
Turning the Tempo knob clockwise doesn't consistently increase the repeats rate.

**Comment by HomoElectromagneticus** [comment]
I'm able to reproduce this bug on my machine. If you turn the tempo knob back and forth a bit, the behavior goes back to normal. Maybe something weird is happening to tmp_data (see Check_Roll_Scale() in BPM_fonction.ino)?

That all being said, I wonder why a user would start from MIDI slave mode and then go to pattern mode...

**Comment by gihaume** [comment]
Yes, but the sequencer transport remains... Maybe should we make this that the tempo and start/stop status get reset so that also prevent the other issue https://github.com/HomoElectromagneticus/Yocto_808/issues/19

**Comment by HomoElectromagneticus** [comment]
@rv0, does it make sense to stop the sequencer if it is started in MIDI slave mode and then a user turns to mode knob to pattern play (MIDI master)? Or do you think that would be confusing / annoying?

**Comment by HomoElectromagneticus** [comment]
This bug has been fixed in [v1.2c](https://github.com/HomoElectromagneticus/Yocto_808/releases/tag/v1.2c)!
