### ISSUE TITLE
Track mode needs (sync) rework 

### ISSUE THREAD

**Issue by rv0** [HomoElectromagneticus/Yocto_808#21]
While the pattern modes have been updated and contain a completely new way of doing sync, the track modes were left untouched. This will lead to unexpected behaviour and possibly bugs when switching from Pattern to Track or Track to Pattern.

**Comment by HomoElectromagneticus** [comment]
Is that something you have any interest in working on as the author of the other sync fixes?

**Comment by rv0** [comment]
Just posting it here so that its a known issue.
I’d love to continue with the firmware development but I can’t allocate time for doing it in the near future.
