### ISSUE TITLE
Decide on coding style

### ISSUE THREAD

**Issue by rv0** [HomoElectromagneticus/Yocto_808#25]
The current source code is a mix of different coding styles.. This does not help with readability.
for example we have:
```
bla() { 
  // code
}
```
and also
```
bla () 
{
  // code
}
```
Not to mention very inconsistent use of spaces

I'd love to do a quick automated reformat of all the code at once, but I don't want to make the decision on my own. Personally coming from a PHP past, the first way is more natural to me, but I think generally the 2nd is used more for C code.. What to choose?

**Comment by rv0** [comment]
Did some "research"..
Apparently I use "Stroustrup" style usually :)

If I do auto format in Sublime Text (Stino plugin), I end up with "Allman" style, .. which to me is hard to read, but my eyes can get used to that.

See https://en.wikipedia.org/wiki/Indentation_style

**Comment by HomoElectromagneticus** [comment]
I find the first way to be much more readable personally!

**Comment by rv0** [comment]
I've set up my SublimeText using SublimeAStyleFormatter with the following settings:

```
{
    // Please visit http://astyle.sourceforge.net/astyle.html for more information
    "options_default": {
        // Default bracket style
        // Can be one of "allman", "bsd", "break", "java", "attach", "kr", "k&r",
        // "k/r" "stroustrup", "whitesmith", "banner", "gnu", "linux", "horstmann",
        // "1tbs", "otbs ", "google", "pico", "lisp", "python", "vtk", or null
        // for default.
        "style": "stroustrup",

        // Tab options
        // "indent": Can be one of "spaces", "tab" "force-tab", "force-tab-x", or null
        // "indent-spaces": Can be either null or numbers
        //
        // While both "indent" or "indent-spaces" are null (default), the indentation options
        // will be retrieved from Sublime Text view settings: `tab_size`, `translate_tabs_to_spaces`:
        //   1. If `translate_tabs_to_spaces` is true, "indent" will be "spaces", otherwise, "tab";
        //   2. "indent-spaces" will equal to `tab_size`.
        "indent": "spaces",
        "indent-spaces": 4,


        // When `style` is "attach", "linux" or "stroustrup", this breaks closing headers
        // (e.g. 'else', 'catch', ...) from their immediately preceding closing brackets.
        // Closing header brackets are always broken with broken brackets, horstmann
        // rackets, indented blocks, and indented brackets.
        "break-closing-brackets": true,

        // Don't break complex statements and multiple statements residing on a single line.
        "keep-one-line-statements": false,
    }
}
```

Still evaluating, but so far I like it, very readable to me. I can add this as a formatter file in the repo so that other people can use these setting automagically, if they use sublime and that plugin.
