### ISSUE TITLE
Stop bar follow when length > 16 steps

### ISSUE THREAD

**Issue by FlavioB79** [HomoElectromagneticus/Yocto_808#29]
Hi.
It's quite annoying to have the pattern follow the bars/steps when it's longer than 16 steps. It is quite difficult and annoying trying to enter the correct steps.
Would be great to have this feature disabled by default and enabled with some key combination.
Thanks for looking into this!
Flavio.

**Comment by rv0** [comment]
Hi

Sorry for the overly late reply, but thats actually already a feature.
Just click and hold the page you wanna keep (01..16/17..32), then press the other page and it will "lock"
similar to unlock
