### ISSUE TITLE
Unable to activate trigger outputs during roll mode

### ISSUE THREAD

**Issue by HomoElectromagneticus** [HomoElectromagneticus/Yocto_808#9]
The two trigger outputs are not able to be rolled like the other instruments.

**Comment by gihaume** [comment]
Don't forget Trigger n°3 as it can be used internally (connected to one of the new voices of the Cocteau mode here).

**Comment by rv0** [comment]
Fixed in https://github.com/HomoElectromagneticus/Yocto_808/pull/22

**Comment by HomoElectromagneticus** [comment]
Nice work, @rv0 !
